apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-financial-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-financial-app
  template:
    metadata:
      labels:
        app: flask-financial-app
    spec:
      containers:
        - name: flask
          image: maddigsys/flask-financial-demo:latest
          ports:
            - containerPort: 5000