apiVersion: v1
kind: Service
metadata:
  name: flask-financial-service
  # annotations: # Optional: for NLB or other specific ELB configurations
  #   service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: NodePort # Changed from NodePort
  selector:
    app: flask-financial-app
  ports:
    - port: 80        # Port the Load Balancer listens on
      targetPort: 5000 # Port on your pods
      # nodePort:  # Not typically specified by you for LoadBalancer type