name: Build and Push Flask App

on:
  push:
    branches: [main]
    paths:
      - 'app.py'
      - 'Dockerfile'
      - '.github/workflows/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Root Image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/flask-vuln-demo:root
          context: .
          file: ./Dockerfile

      - name: Build and Push Non-Root Image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/flask-vuln-demo:nonroot
          context: .
          file: ./Dockerfile
          build-args: |
            RUN_AS_NON_ROOT=true
